// QuotesVault.ts
// Extracted from crypto_quotes_vault.txt

export const QUOTES = [
  "Every block is a new chance, every wallet a new story.",
  "Luck is a whisper on the chain, heard only by the bold.",
  "Not your keys, not your dreams.",
  "The house always wins, but fortune sometimes tips the scales.",
  "Patience is the secret weapon of every degen.",
  "Rug pulls are lessons, not losses.",
  "Odds are just numbers until you make them poetry.",
  "Web3 is a midnight gamble, where hope meets hash.",
  "Jackpots wait for those who dare to dive deep.",
  "Flip a coin, and let fate decide.",
  "All in is a promise, all gone is a memory.",
  "Volatility is the only constant in crypto.",
  "Bet small, win big, and let the chain remember.",
  "If you can't spot the whale, maybe you are one.",
  "Let the market come to you, like rain to the ocean.",
  "Every block writes a new verse in the chain's song.",
  "The best time to cash out is when your heart says so.",
  "Luck dances when you least expect it.",
  "May your flips be green and your rugs be rare.",
  "No KYC, no sign-ups, just you and the chain.",
  "Your wallet, your winnings, your story.",
  "On-chain odds are honest, but your heart may not be.",
  "Instant payouts for instant legends.",
  "Provably fair, emotionally wild.",
  "The blockchain remembers every move.",
  "Spin, win, withdraw, repeat.",
  "Not your keys, not your cheese.",
  "Luck prefers cold wallets.",
  "No middlemen, just you and the math.",
  "Decentralized, degen-centralized, always peer-to-peer.",
  "Every block is a fair shot and a fresh start.",
  "Let your soul be your signature.",
  "Transparency builds trust, RNG tests it.",
  "Your bankroll is yours, your tilt is not.",
  "In Web3, regrets are instant too.",
  "Audit the odds, not the losses.",
  "Fortune favors the bold and the gas-efficient.",
  "In this game, you're both player and poet.",
  "Chase the wallet, not the losses.",
  "Every block is a heartbeat of chance.",
  "Each block is a risk rewritten.",
  "Wallets give and take, like old friends.",
  "Without crypto, the night is quiet.",
  "Non-custodial is fleeting, risk lingers.",
  "Let your heart be the oracle.",
  "Provably fair is the chain's promise.",
  "Staking is a slow waltz.",
  "Without instant wins, the longing grows.",
  "Degens are the poets of Web3.",
  "Luck is a river, every block a current.",
  "Crypto changes with every sunrise.",
  "Chase staking, not losses.",
  "Trust your intuition, not just crypto.",
  "Provably fair moves fast, heartbreak faster.",
  "Every block is a coin toss.",
  "Bragging rights are the stories you tell.",
  "Let conviction be your compass.",
  "Risk is a shadow ahead of your tilt.",
  "Without KYC, every heart is a secret wallet.",
  "Chase the thrill, not the losses.",
  "If you can't beat the wallet, become its poet.",
  "Chase crypto, not losses.",
  "The chain is a masquerade, every mask a story.",
  "Without degens, the chain is silent.",
  "Volatility is a lover's quarrel.",
  "If you can't beat the odds, write your own.",
  "KYC is fleeting, bragging rights last.",
  "Trust the poetry of your own risk.",
  "Let your own current carry you.",
  "Without jackpots, the night is just another evening.",
  "Your heart writes the chorus.",
  "Bragging rights echo in eternity.",
  "Without volatility, the dance is slow.",
  "Each payout is a whispered promise.",
  "Without risk, the story is unwritten.",
  "Degens move faster than regret.",
  "If you can't tame volatility, waltz with it.",
  "Staking is a slow burn.",
  "Wallets are verses, Web3 is the song.",
  "Without gas fees, the chain is silent.",
  "Every block is a KYC you never signed.",
  "Staking moves fast, longing faster.",
  "Without volatility, the serenade is incomplete.",
  "Each outcome, a secret kept.",
  "Let conviction be your serenade.",
  "Not all provably fair are written the same.",
  "Become crypto's muse.",
  "Dance without a mask.",
  "On-chain is the stage, your heart the actor.",
  "Crypto is fleeting, legend lasts.",
  "Without blockchain, the serenade is unsung.",
  "Odds are secrets kept by the chain.",
  "Blockchain gives and takes, each block a memory.",
  "KYC is fleeting, bragging rights are the refrain.",
  "Without non-custodial, the story is unfinished.",
  "Degens move faster than memory.",
  "If you can't outswim whales, become the tide.",
  "Every block is a whale's sigh.",
  "Without gamble, the night is silent.",
  "Let volatility write your song.",
  "Instant wins move fast, longing faster.",
  "Risk is the chain's invitation to dance.",
  "Not all provably fair are sung the same.",
  "Blockchain is the backdrop, longing is the play.",
  "If you can't catch jackpots, become the dreamer.",
  "Every block is a wallet's confession.",
  "Without blockchain, the serenade is a whisper.",
  "Non-custodial is the overture, your story the symphony.",
  "On-chain is the echo, longing is the voice.",
  "Provably fair is the prelude, your heart the refrain.",
  "Without jackpots, the night is just another verse.",
  "Non-custodial is fleeting, legend lasts.",
  "Risk is a shadow, tilt is the dance.",
  "Luck moves fast, heartbreak faster.",
  "Every block is a jackpot's heartbeat.",
  "Become the memory.",
  "Let patience be your serenade.",
  "Write your own ballad.",
  "Gas fees are the price of a midnight waltz.",
  "Gamble is the chain's invitation to dance.",
  "Blockchain gives and takes, each block a sigh.",
  "Every block is a whale's lullaby.",
  "Staking is a slow burn, each ember a memory.",
  "On-chain is fleeting, bragging rights echo.",
  "Wallets are fleeting, legend lasts.",
  "Let conviction be your serenade.",
  "Every block is a wallet's secret.",
  "Let longing be your guide.",
  "On-chain is the overture, longing is the song.",
  "Odds move fast, heartbreak faster.",
  "Without crypto, the serenade is silent.",
  "Wallets give and take, each transaction a confession.",
  "Odds move fast, longing faster.",
  "Chase gas fees, not losses.",
  "Write your own verse.",
  "Chase KYC, not losses.",
  "Without gamble, the serenade is unsung.",
  "Write your own refrain.",
  "Without staking, the waltz is unfinished.",
  "Instant wins are fleeting, legend lasts.",
  "Gas fees give and take, each swing a quarrel.",
  "Chase volatility, not losses.",
  "Not all provably fair are written the same.",
  "Without odds, the serenade is silent.",
  "Not all payouts are sung the same.",
  "Blockchain gives and takes, each block a memory.",
  "Without wallet, the serenade is silent.",
  "Every block is a gas fee's confession.",
  "Whales are the chain's lullaby.",
  "Every block is a risk's heartbeat.",
  "Every block is volatility's sigh.",
  "Let patience be your serenade.",
  "Whales move fast, heartbreak faster.",
  "Degens give and take, each tilt a new verse.",
  "Without provably fair, the serenade is unfinished.",
  "Let longing be your guide.",
  "Instant wins are the chain's way of saying 'I love you.'",
  "Crypto moves fast, heartbreak faster.",
  "Volatility gives and takes, each swing a sigh.",
  "Write your own melody.",
  "Not all instant wins are sung the same.",
  "Provably fair moves fast, longing faster.",
  "Write your own verse.",
  "Write your own confession.",
  "Jackpots are the chain's way of dreaming.",
  "Write your own refrain.",
  "Jackpots are the chain's lullaby.",
  "Let longing be your serenade.",
  "Whales move fast, heartbreak faster.",
  "Without provably fair, the serenade is unfinished.",
  "Degens are the chain's poets.",
  "Without blockchain, the serenade is silent.",
  "Let conviction be your serenade.",
  "Crypto gives and takes, each swing a sigh.",
  "Write your own verse.",
  "Chase gas fees, not losses.",
  "Let patience be your serenade.",
  "Write your own melody.",
  "Not all wallets are sung the same.",
  "Write your own refrain."
];
