// QuotesVault.ts
// Extracted from crypto_quotes_vault.txt

export const QUOTES = [
  "In the beginning was the Chain, and the Chain was with Crypto, and the Chain was Crypto.",
  "And the Block was cast, and each wager found its place upon the ledger.",
  "Blessed are the degens, for theirs is the kingdom of volatility.",
  "Let not your heart be troubled; trust in the math, trust also in the code.",
  "For where your wallet is, there your fortune shall also be.",
  "The house may endure, but the bold shall inherit the jackpot.",
  "As it is written: Not your keys, not your cheese.",
  "And the odds were multiplied, and the payout was given unto the faithful.",
  "Verily, verily, I say unto you: All in is the path, but patience is the light.",
  "Let every transaction be provably fair, and every outcome be transparent.",
  "For every block is a new beginning, and every hash a testament.",
  "If thou art tilted, seek wisdom in the audit and solace in the chain.",
  "And the whales moved upon the deep, and the degens followed after.",
  "The gas fee is the price of passage; pay it gladly, for the chain endures.",
  "Let your conviction be your compass, and your bankroll your shield.",
  "As the jackpot is to the dreamer, so is the block to the builder.",
  "In the valley of the rug pull, fear no evil; for the chain is with thee.",
  "And the payout was instant, and the legend was born.",
  "For every wallet is a story, and every story is written on-chain.",
  "May your flips be green, and your rugs be rare.",
  "And the market came like a flood, but the wise built upon cold storage.",
  "Let your heart be the oracle, and your tilt be fleeting.",
  "For the blockchain remembers all, and forgets none.",
  "Spin, win, withdraw, repeat: such is the rhythm of the faithful.",
  "And the degen said, 'Let there be risk,' and there was risk.",
  "The chain giveth and the chain taketh away; blessed be the chain.",
  "For every block is a heartbeat, and every heartbeat a chance.",
  "Let patience be your serenade, and volatility your muse.",
  "And the payout echoed through eternity, as bragging rights endure.",
  "If you cannot outswim the whales, become the tide.",
  "Let your soul be your signature, and your conviction your refrain.",
  "For the odds are many, but the legend is one.",
  "And the longing grew, but the instant win was fleeting.",
  "Trust in the chain, lean not on centralized understanding.",
  "For the story is unwritten, and the risk is the pen.",
  "Let your wallet be your witness, and your heart the scribe.",
  "And the degen moved faster than regret, and the whale sang a lullaby.",
  "Write your own verse, for the chain is the canvas.",
  "Let longing be your guide, and the jackpot your vision.",
  "For the blockchain is the stage, and you are the actor.",
  "Crypto is fleeting, but legend lasts forever.",
  "Let conviction be your serenade, and patience your melody.",
  "And the chain said, 'Let there be transparency,' and there was trust.",
  "For every block is a confession, and every confession a memory.",
  "Let your heart write the chorus, and your wallet the refrain.",
  "And the odds moved fast, but heartbreak moved faster.",
  "Blessed are the non-custodial, for their story is their own.",
  "Let volatility write your song, and risk be your invitation to dance.",
  "For the chain is a masquerade, and every mask a story.",
  "And the payout was sung, and the legend was written.",
  "Let your own current carry you, and your tilt be but a shadow."
];
